version: '3'
services:
  piast-backend:
    build: ./backend
    ports:
      - 2137:2137
    volumes:
      - ./backend/:/usr/src/app
    depends_on:
      - piast-db
  piast-db:
    image: mariadb:10.4
    ports:
      - 3306:3306
