version: '3'
services:
  piast-backend:
    build: ./backend
    ports:
      - 2137:2137
    volumes:
      - ./backend/:/usr/src/app
    depends_on:
      - piast-db
  piast-db:
    build: ./database
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d/
